# Generated by Django 4.2.7 on 2023-11-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_alter_customuser_role_alter_customuser_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='token',
            new_name='token_wpp',
        ),
        migrations.RenameField(
            model_name='tokenwpp',
            old_name='token_wpp',
            new_name='token',
        ),
    ]
