# Generated by Django 4.2.7 on 2023-11-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_rename_token_customuser_token_wpp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='token_wpp',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='tokenwpp',
            old_name='token',
            new_name='token_wpp',
        ),
    ]
