# Generated by Django 4.2.7 on 2024-09-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_rename_group_wppgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wppgroup',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user_1', 'user1'), ('user_2', 'user2'), ('user_3', 'user3')], max_length=8),
        ),
        migrations.AlterField(
            model_name='tokenwpp',
            name='token_wpp',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
